var sourceDetails_name;
var sourceDetails_driver;
var sourceDetails_protocol;
var sourceDetails_username;
var sourceDetails_password;
var ExecitionSequence_query_counter;
var ExecitionSequence_query;
var TextTransformation_Attribute;
var TextTransformation_sourcePattern;
var TextTransformation_DestinationPattern;
var ArthimeticTransformation_Attribute;
var ArthimeticTransformation_formulae;
var DestinationDetails_name;
var DestinationDetails_driver;
var DestinationDetails_protocol;
var DestinationDetails_username;
var DestinationDetails_password;
// var TransformationDetails = [[], []];
var xmldata=['<?xml version="1.0" encoding="utf-8"?>'];
xmldata.push("<ETL>");
xmldata.push("<sourceDetails>");
xmldata.push("<sourceinfo>");
xmldata.push("<name>");
xmldata.push(sourceDetails_name);
xmldata.push("</name>");
xmldata.push("<driver>");
xmldata.push(sourceDetails_driver);
xmldata.push("</driver>");
xmldata.push("<protocol>");
xmldata.push(sourceDetails_protocol);
xmldata.push("</protocol>");
xmldata.push("<username>");
xmldata.push(sourceDetails_username);
xmldata.push("</username>");
xmldata.push("<password>");
xmldata.push(sourceDetails_password);
xmldata.push("</password>");
xmldata.push("</sourceinfo>");
xmldata.push("</sourceDetails>");
xmldata.push("<ExecutionSequence>");
for(var i = 0; i < ExecitionSequence_query_counter; i++){
    xmldata.push("<Query>");
    xmldata.push(ExecitionSequence_query);
    xmldata.push("</Query>");
}
xmldata.push("</ExecutionSequence>");
xmldata.push("<TransformationDetails>");
xmldata.push("<TextTransformation>");
xmldata.push("<Attribute>");
xmldata.push(TextTransformation_Attribute);
xmldata.push("</Attribute>");
xmldata.push("<sourcePattern>");
xmldata.push(TextTransformation_sourcePattern);
xmldata.push("</sourcePattern>");
xmldata.push("<DestinationPattern>");
xmldata.push(TextTransformation_DestinationPattern);
xmldata.push("</DestinationPattern>");
xmldata.push("</TextTransformation>");
xmldata.push("<ArthimeticTransformation>");
xmldata.push("<Attribute>");
xmldata.push(ArthimeticTransformation_Attribute);
xmldata.push("</Attribute>");
xmldata.push("<arthimeticformulae>");
xmldata.push(ArthimeticTransformation_formulae);
xmldata.push("<arthemicformulae>");
xmldata.push("</ArthimeticTransformation>");
xmldata.push("</TransformationDetails>");
xmldata.push("<DestinationDetails>");
xmldata.push("<DestinationInfo>");
xmldata.push("<name>");
xmldata.push(DestinationDetails_name);
xmldata.push("</name>");
xmldata.push("<driver>");
xmldata.push(DestinationDetails_driver);
xmldata.push("</driver>");
xmldata.push("<protocol>");
xmldata.push(DestinationDetails_protocol);
xmldata.push("</protocol>");
xmldata.push("<username>");
xmldata.push(DestinationDetails_username);
xmldata.push("</username>");
xmldata.push("<password>");
xmldata.push(DestinationDetails_password);
xmldata.push("</password>");
xmldata.push("</DestinationInfo>");
xmldata.push("</DestinationDetails>");
xmldata.push("</ETl>");
